name: resilience_map
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.2.4
  - pandas=2.2.3
  - matplotlib=3.10.1
  - geopandas
  - pip
  - pip:
    - PyYAML
    - requests
    - anthropic
    - pypdf>=3.0.0
    - tqdm
    - tiktoken
